class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lesson, only: [ :show ]

  def index
    @lessons = current_user.lessons.order(created_at: :desc)
  end

  def show
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = current_user.lessons.build(lesson_params)

    groq = GroqClient.new
    ai_response = groq.generate_lesson(
      topic: @lesson.topic,
      level: @lesson.level
    )

    # If HTTP or client error
    if ai_response["error"].present?
      flash.now[:alert] = "AI Error: #{ai_response['error']}"
      return render :new
    end

    # Extract the actual model content safely
    raw_text = ai_response.dig("choices", 0, "message", "content")

    if raw_text.blank?
      flash.now[:alert] = "AI returned empty response."
      return render :new
    end

    # Parse JSON generated by the model
    begin
      parsed = JSON.parse(raw_text)
    rescue JSON::ParserError
      flash.now[:alert] = "AI returned invalid JSON. Try again."
      return render :new
    end

    @lesson.content  = parsed["lesson"]
    @lesson.metadata = parsed["quiz"]

    if @lesson.save
      flash[:notice] = "Lesson generated successfully."
      redirect_to @lesson
    else
      flash.now[:alert] = "Failed to save lesson."
      render :new
    end
  end

  private

  def set_lesson
    @lesson = current_user.lessons.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to lessons_path, alert: "Lesson not found."
  end

  def lesson_params
    params.require(:lesson).permit(:topic, :level)
  end
end
